version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pokemondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DB_NAME: pokemondb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: admin
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432

volumes:
  postgres_data: